### ISSUE TITLE
update prom exporter to use common bitnami charts

### ISSUE THREAD

**Issue by jamiezieziula** [PrefectHQ/prometheus-prefect-exporter#32]

**Comment by mitchnielsen** [comment]
Looking into this a bit as it was on my "Good first issues" onboarding list:

- The Helm chart appears to be in https://github.com/PrefectHQ/prefect-helm/tree/main/charts/prometheus-prefect-exporter
- Looks like the common chart was first introduced as a dependency in https://github.com/PrefectHQ/prefect-helm/pull/310
- I'm guessing this issue intends to expand on the usage of the common library chart from Bitnami to reduce the amount of configuration we have to define

Let me know if I missed anything / got anything wrong @jamiezieziula 👍🏼
