### ISSUE TITLE
Disabling pagination leads to data loss

### ISSUE THREAD

**Issue by ubiquitousbyte** [PrefectHQ/prometheus-prefect-exporter#53]
### Describe the bug a clear and concise description of what the bug is.

If the user sets the `PAGINATION_ENABLED` environment variable to `false`, then `_get_with_pagination` should only fetch one page from the Prefect Server. Currently, the logic prematurely exits the pagination loop - **before it populates the all_items list with the fetched data**. This means that all deployments with `PAGINATION_ENABLED` set to `false` will not get any metrics back. The [logic](https://github.com/PrefectHQ/prometheus-prefect-exporter/blob/main/metrics/api_metric.py#L75C1-L86C28) should be refactored to:

```python
curr_page_items = resp.json()
# If the current page is empty, break the loop
if not curr_page_items:
    break

# The current page is not empty, extend our item list.
all_items.extend(curr_page_items)

# If pagination is not used, break the loop
if not enable_pagination:
   break

offset += limit
```

### Application name

prometheus-prefect-exporter

### Application version

1.6.1

**Comment by zzstoatzz** [comment]
closed by https://github.com/PrefectHQ/prometheus-prefect-exporter/pull/54
